apiVersion: apps/v1
kind: Deployment
metadata:
  name: darwin-2
  namespace: darwin     # Specify the namespace here
spec:
  selector:
    matchLabels:
      run: darwin-2
  replicas: 2
  template:
    metadata:
      labels:
        run: darwin-2
    spec:
      containers:
      - name: darwin-container-2
        image: httpd:2.42.1
      - name: new-container       # Name for the additional container
        image: nginx:0.25.2 
