apiVersion: apps/v1
kind: Deployment2
metadata:
  name: darwin
  namespace: darwin     # Specify the namespace here
spec:
  selector:
    matchLabels:
      run: darwin
  replicas: 2
  template:
    metadata:
      labels:
        run: darwin
    spec:
      containers:
      - name: darwin-container
        image: httpd:2.42.1
