apiVersion: v1
kind: Service
metadata:
  name: darwin
  namespace: darwin     # Specify the namespace here
  labels:
    run: darwin
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: darwin

